// Sample menu data for the AR menu app

export const categories = [
  { id: "starters", name: "Starters" },
  { id: "main", name: "Main Course" },
  { id: "desserts", name: "Desserts" },
  { id: "beverages", name: "Beverages" },
  { id: "salads", name: "Salads" },
  { id: "soups", name: "Soups" },
];

export const dishes = [
  {
    id: "spring-rolls",
    name: "Spring Rolls",
    category: "starters",
    price: 149,
    description: "Crispy rolls stuffed with veggies.",
    nutrition: { protein: 3, carbs: 15, fat: 5 },
    quantity: "4 pieces",
    bestseller: true,
    veg: true,
    image:
      "https://d1mxd7n691o8sz.cloudfront.net/static/recipe/recipe/2023-12/Vegetable-Spring-Rolls-2-1-906001560ca545c8bc72baf473f230b4_thumbnail_170.jpeg",
  },
  {
    id: "grilled-chicken",
    name: "Grilled Chicken",
    category: "main",
    price: 349,
    description: "Juicy grilled chicken breast with herbs.",
    nutrition: { protein: 30, carbs: 2, fat: 8 },
    quantity: "1 plate",
    bestseller: true,
    image:
      "https://www.spiceindiaonline.com/wp-content/uploads/2021/05/Tandoori-Chicken-20.jpg",
  },
  {
    id: "cheesecake",
    name: "Cheesecake",
    category: "desserts",
    price: 499,
    description: "Creamy cheesecake with a graham crust.",
    nutrition: { protein: 6, carbs: 28, fat: 18 },
    quantity: "1 slice",
    bestseller: false,
    veg: true,
    image:
      "https://butternutbakeryblog.com/wp-content/uploads/2020/04/cheesecake-slice.jpg",
  },
  {
    id: "caesar-salad",
    name: "Caesar Salad",
    category: "salads",
    price: 275,
    description: "Classic Caesar salad with parmesan and croutons.",
    nutrition: { protein: 7, carbs: 12, fat: 10 },
    quantity: "1 bowl",
    bestseller: true,
    veg: false,
    image:
      "https://www.allrecipes.com/thmb/mXZ0Tulwn3x9_YB_ZbkiTveDYFE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/229063-Classic-Restaurant-Caesar-Salad-ddmfs-4x3-231-89bafa5e54dd4a8c933cf2a5f9f12a6f.jpg",
  },
  {
    id: "tomato-soup",
    name: "Tomato Soup",
    category: "soups",
    price: 149,
    description: "Rich and creamy tomato soup.",
    nutrition: { protein: 2, carbs: 14, fat: 3 },
    quantity: "1 bowl",
    bestseller: false,
    veg: true,
    image:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/11/tomato-soup-recipe.jpg",
  },
  {
    id: "lemonade",
    name: "Lemonade",
    category: "beverages",
    price: 49,
    description: "Freshly squeezed lemonade.",
    nutrition: { protein: 0, carbs: 25, fat: 0 },
    quantity: "1 glass",
    bestseller: false,
    veg: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3CxYonC8qV5pNC6NDv66GJu7zocUkRnPCyw&s",
  },
  {
    id: "mango-smoothie",
    name: "Mango Smoothie",
    category: "beverages",
    price: 249,
    description: "Chilled mango smoothie with yogurt.",
    nutrition: { protein: 4, carbs: 30, fat: 2 },
    quantity: "1 glass",
    bestseller: true,
    veg: true,
    image:
      "https://www.kerryfoodservice.com/cdn/shop/files/DVGMangoSmoothie_015_SmoothieMix_Photoshoot_2024_Recipe_1000x.png?v=1716408442",
  },
  {
    id: "greek-salad",
    name: "Greek Salad",
    category: "salads",
    price: 349,
    description: "Salad with feta, olives, cucumber, and tomatoes.",
    nutrition: { protein: 5, carbs: 10, fat: 9 },
    quantity: "1 bowl",
    bestseller: false,
    veg: true,
    image:
      "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/greek_salad_16407_16x9.jpg",
  },
  {
    id: "veg-manchow-soup",
    name: "Veg Manchow Soup",
    category: "soups",
    price: 149,
    description: "Spicy Indo-Chinese soup with crispy noodles.",
    nutrition: { protein: 3, carbs: 18, fat: 4 },
    quantity: "1 bowl",
    bestseller: true,
    veg: true,
    image:
      "https://i0.wp.com/asthaskitchendilse.wordpress.com/wp-content/uploads/2022/02/wp-1643806181558.jpg?fit=900%2C1200&ssl=1",
  },
  {
    id: "brownie",
    name: "Chocolate Brownie",
    category: "desserts",
    price: 119,
    description: "Rich chocolate brownie with walnuts.",
    nutrition: { protein: 4, carbs: 32, fat: 15 },
    quantity: "1 piece",
    bestseller: true,
    veg: true,
    image:
      "https://icecreambakery.in/wp-content/uploads/2024/12/Brownie-Recipe-with-Cocoa-Powder.jpg",
  },
];
